### PR TITLE
Namespace is mysql-multi not mysql_multi

### PR DESCRIPTION
**Pull request by schwing**
This is to fix this search: https://github.com/AutomationSupport/tomcatstack/blob/master/recipes/tomcat.rb#L28

### CODE REVIEW

**Comment by martinb3** [comment]
LGTM once it passes tests. It will need to be released and then version bumped.

**Comment by cybermerc** [comment]
retest this please

**Comment by schwing** [comment]
The upstream mysql cookbook was converted to a LWRPs in version 6.0.0. The last PR on mysql-multi was around v5.6.1, so it hasn't been tested against the 6.x.x upstream until now. Looks like `default['mysql']['service_name'] = 'default'` may need to be added to mysql-multi for compatibility. This was previously set by the recipe in [attributes/default.rb in v5.6.1](https://github.com/opscode-cookbooks/mysql/blob/v5.6.1/attributes/default.rb#L2) but the only remaining reference to this upstream is in the test fixtures: https://github.com/opscode-cookbooks/mysql/blob/master/test/fixtures/cookbooks/mysql_service_test/attributes/default.rb

**Comment by cybermerc** [comment]
This cookbook will not work with MySQL community version 6.x due to numerous changes. We are going to stay on version 5.x until such time 6.x becomes more stable. It has not been properly pinned, I will do this today and get this retested.

**Comment by cybermerc** [comment]
moving this to a new PR to be able to add changes... https://github.com/rackspace-cookbooks/mysql-multi/pull/41

closing this one

**Pull request closed without merging**
